const LOCAL_STORAGE_KEY = "IsmaCortGtz_fasty-task_";

export const LS_HOMEWORK_API = LOCAL_STORAGE_KEY + "HOMEWORK_API";
export const LS_HOMEWORK_DATA = LOCAL_STORAGE_KEY + "HOMEWORK_DATA";
export const LS_HOMEWORK_FINISHED = LOCAL_STORAGE_KEY + "HOMEWORK_FINISHED";